spring.application.name=backend
spring.config.import=optional:file:.env[.properties]
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/smartcampus}
spring.data.mongodb.database=smartcampus
spring.data.mongodb.auto-index-creation=true
